import { verifyUser } from "../actions/auth/verify_user";
import { redirect } from "next/navigation";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ProtectedLayout({children}: Readonly<{children: React.ReactNode}>) {
    const userVerified = await verifyUser();
    console.log("protected layout called, user verified:", userVerified)
    if (!userVerified) {
        redirect("/login");
    }
    return (
        children
    );
}