import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { AuthProvider } from "./providers";
import { Toaster } from "sonner";
import { auth } from "@/_lib/firebase";
import { verifyUser } from "./actions/auth/verify_user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
    <AuthProvider>
      <body className="min-h-full flex flex-col">
        <Header></Header>
        {children}
        <Toaster
          richColors
          position="top-right"
          toastOptions={{ style: { borderRadius: "12px" } }}
        />
        </body>
    </AuthProvider>
    </html>

  );
}
